# Project-owned chat_program configuration generated by Say Count.
# This file is intentionally never overwritten after installation.

default say_count_chat_initial_channel = "#general"

init 1 python:
    def say_count_reset_chats():
        reset_chats()
        channel = store.say_count_chat_initial_channel
        store.current_window = channel
        store.active_window = channel
        store.last_window = channel
        if channel not in store.channels:
            store.channels[channel] = []
        if channel not in store.channels_new_message:
            store.channels_new_message[channel] = False
        if channel not in store.channels_last_sender:
            store.channels_last_sender[channel] = None
