#include "core/renpy_runtime.h"

#include <cctype>
#include <filesystem>
#include <fstream>
#include <limits>
#include <sstream>

namespace say_count {
namespace {

namespace fs = std::filesystem;
constexpr std::string_view kMarker = "# Generated by Say Count for state presets and playthrough coverage.";
constexpr std::string_view kPresetMagic = "SAY-COUNT-RUNTIME-PRESETS-1";

class Validator {
public:
    explicit Validator(std::string_view text) : text_(text) {}
    RuntimeStateValidation Run() {
        Space();
        if (!Object(true)) return {false, error_};
        Space();
        return position_ == text_.size() ? RuntimeStateValidation{true, {}}
                                         : RuntimeStateValidation{false, "Unexpected data after the state object."};
    }
private:
    void Space() { while (position_ < text_.size() && std::isspace(static_cast<unsigned char>(text_[position_]))) ++position_; }
    bool Take(char value) { Space(); if (position_ < text_.size() && text_[position_] == value) { ++position_; return true; } return false; }
    bool String(std::string* decoded = nullptr) {
        Space();
        if (position_ >= text_.size() || text_[position_++] != '"') return Fail("Expected a JSON string.");
        while (position_ < text_.size()) {
            const char c = text_[position_++];
            if (c == '"') return true;
            if (static_cast<unsigned char>(c) < 0x20) return Fail("Invalid control character in JSON string.");
            if (c == '\\') {
                if (position_ >= text_.size()) return Fail("Incomplete JSON escape.");
                const char escaped = text_[position_++];
                if (escaped == 'u') {
                    for (int i = 0; i < 4; ++i)
                        if (position_ >= text_.size() || !std::isxdigit(static_cast<unsigned char>(text_[position_++])))
                            return Fail("Invalid Unicode escape.");
                    if (decoded) decoded->push_back('_');
                } else if (std::string_view("\"\\/bfnrt").find(escaped) == std::string_view::npos)
                    return Fail("Invalid JSON escape.");
                else if (decoded) decoded->push_back(escaped);
            } else if (decoded) decoded->push_back(c);
        }
        return Fail("Unclosed JSON string.");
    }
    bool Number() {
        Space(); const std::size_t begin = position_;
        if (position_ < text_.size() && text_[position_] == '-') ++position_;
        if (position_ >= text_.size()) return Fail("Invalid JSON number.");
        if (text_[position_] == '0') ++position_;
        else if (std::isdigit(static_cast<unsigned char>(text_[position_])))
            while (position_ < text_.size() && std::isdigit(static_cast<unsigned char>(text_[position_]))) ++position_;
        else return Fail("Invalid JSON number.");
        if (position_ < text_.size() && text_[position_] == '.') {
            ++position_; const auto digits = position_;
            while (position_ < text_.size() && std::isdigit(static_cast<unsigned char>(text_[position_]))) ++position_;
            if (digits == position_) return Fail("Invalid JSON number.");
        }
        if (position_ < text_.size() && (text_[position_] == 'e' || text_[position_] == 'E')) {
            ++position_; if (position_ < text_.size() && (text_[position_] == '+' || text_[position_] == '-')) ++position_;
            const auto digits = position_;
            while (position_ < text_.size() && std::isdigit(static_cast<unsigned char>(text_[position_]))) ++position_;
            if (digits == position_) return Fail("Invalid JSON number.");
        }
        return position_ > begin;
    }
    bool Value() {
        Space(); if (position_ >= text_.size()) return Fail("Expected a JSON value.");
        if (text_[position_] == '"') return String();
        if (text_[position_] == '{') return Object(false);
        if (text_[position_] == '[') {
            ++position_; Space(); if (Take(']')) return true;
            while (true) { if (!Value()) return false; if (Take(']')) return true; if (!Take(',')) return Fail("Expected ',' in array."); }
        }
        for (const auto literal : {std::string_view("true"), std::string_view("false"), std::string_view("null")})
            if (text_.substr(position_, literal.size()) == literal) { position_ += literal.size(); return true; }
        return Number();
    }
    bool Object(bool root) {
        if (!Take('{')) return Fail("Runtime state must be a JSON object.");
        Space(); if (Take('}')) return true;
        while (true) {
            std::string key; if (!String(&key)) return false;
            if (root && (key.empty() || !(std::isalpha(static_cast<unsigned char>(key[0])) || key[0] == '_')))
                return Fail("Runtime state keys must be valid variable names.");
            if (root) for (const char c : key.substr(1))
                if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_'))
                    return Fail("Runtime state keys must be valid variable names.");
            if (!Take(':')) return Fail("Expected ':' after object key.");
            if (!Value()) return false;
            if (Take('}')) return true;
            if (!Take(',')) return Fail("Expected ',' in object.");
        }
    }
    bool Fail(std::string message) { if (error_.empty()) error_ = std::move(message); return false; }
    std::string_view text_; std::size_t position_ = 0; std::string error_;
};

void Blob(std::ostream& out, std::string_view value) {
    out << value.size() << '\n'; out.write(value.data(), static_cast<std::streamsize>(value.size())); out.put('\n');
}

bool ReadBlob(std::istream& in, std::string& value) {
    std::string line; if (!std::getline(in, line)) return false;
    std::size_t length = 0;
    try { length = std::stoull(line); } catch (...) { return false; }
    if (length > static_cast<std::size_t>(std::numeric_limits<std::streamsize>::max())) return false;
    value.resize(length); in.read(value.data(), static_cast<std::streamsize>(length));
    return in.gcount() == static_cast<std::streamsize>(length) && in.get() == '\n';
}

}  // namespace

RuntimeStateValidation validate_runtime_state(std::string_view json) { return Validator(json).Run(); }

std::string renpy_runtime_source() {
    return std::string(kMarker) + R"(
init -999 python:
    import json, os
    _say_count_state = json.loads(os.environ.get("SAY_COUNT_STATE", "{}"))
    for _say_count_key, _say_count_value in _say_count_state.items():
        setattr(renpy.store, _say_count_key, _say_count_value)
    _say_count_coverage_path = os.environ.get("SAY_COUNT_COVERAGE", "")
    def _say_count_record_label(label, abnormal):
        if _say_count_coverage_path:
            with open(_say_count_coverage_path, "a", encoding="utf-8") as _say_count_coverage_file:
                _say_count_coverage_file.write(json.dumps({"label": label}) + "\n")
    config.label_callbacks.append(_say_count_record_label)
)";
}

bool write_renpy_runtime(const std::string& game_directory, std::string* error) {
    if (error) error->clear();
    const fs::path destination = fs::path(game_directory) / "say_count_runtime.rpy";
    std::error_code ec;
    if (!fs::is_directory(game_directory, ec)) { if (error) *error = "The game directory does not exist."; return false; }
    if (fs::exists(destination, ec)) {
        std::ifstream existing(destination, std::ios::binary); std::string first;
        std::getline(existing, first);
        if (!existing || first != kMarker) {
            if (error) *error = "say_count_runtime.rpy exists but is not owned by Say Count.";
            return false;
        }
    }
    const fs::path temporary = destination.string() + ".tmp";
    std::ofstream output(temporary, std::ios::binary | std::ios::trunc);
    output << renpy_runtime_source(); output.close();
    if (!output) { fs::remove(temporary, ec); if (error) *error = "Could not write the runtime helper."; return false; }
    fs::rename(temporary, destination, ec);
    if (ec) {
        fs::remove(destination, ec); ec.clear(); fs::rename(temporary, destination, ec);
    }
    if (ec) { fs::remove(temporary, ec); if (error) *error = "Could not finalize the runtime helper."; return false; }
    return true;
}

std::map<std::string, std::string> RuntimePresetStore::Load(std::string* error) const {
    if (error) error->clear();
    std::map<std::string, std::string> result;
    std::ifstream input(path_, std::ios::binary);
    if (!input) return result;
    std::string magic; if (!std::getline(input, magic) || magic != kPresetMagic) {
        if (error) *error = "Invalid runtime preset file.";
        return {};
    }
    std::string line; if (!std::getline(input, line)) { if (error) *error = "Invalid runtime preset count."; return {}; }
    std::size_t count = 0; try { count = std::stoull(line); } catch (...) { if (error) *error = "Invalid runtime preset count."; return {}; }
    for (std::size_t i = 0; i < count; ++i) {
        std::string name, json; if (!ReadBlob(input, name) || !ReadBlob(input, json) || !validate_runtime_state(json).valid) {
            if (error) *error = "Invalid runtime preset data.";
            return {};
        }
        result[name] = json;
    }
    return result;
}

bool RuntimePresetStore::Save(const std::map<std::string, std::string>& presets, std::string* error) const {
    if (error) error->clear();
    for (const auto& [name, json] : presets)
        if (name.empty() || !validate_runtime_state(json).valid) { if (error) *error = "Invalid runtime preset."; return false; }
    std::error_code ec; fs::create_directories(fs::path(path_).parent_path(), ec);
    if (ec) { if (error) *error = "Could not create the preset directory."; return false; }
    const fs::path temporary = path_ + ".tmp";
    std::ofstream output(temporary, std::ios::binary | std::ios::trunc);
    output << kPresetMagic << '\n' << presets.size() << '\n';
    for (const auto& [name, json] : presets) { Blob(output, name); Blob(output, json); }
    output.close();
    if (!output) { fs::remove(temporary, ec); if (error) *error = "Could not write runtime presets."; return false; }
    fs::rename(temporary, path_, ec);
    if (ec) { fs::remove(path_, ec); ec.clear(); fs::rename(temporary, path_, ec); }
    if (ec) { fs::remove(temporary, ec); if (error) *error = "Could not finalize runtime presets."; return false; }
    return true;
}

}  // namespace say_count
